export const skills = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "React Hooks",
  "styled-components",
  "Responsive Web Design",
  "Markdown",
  "Immutability",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "React Router",
  "Scrum",
  "Redux Toolkit",
  "Error handling",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Trello",
  "Working with API (fetch, axios)",
  "NPM",
];

export const goals = [
  "Node.js",
  "MySQL",
  "MongoDB",
  "Bootstrap",
  "Tailwind",
  "jQuery",
  "Vue.js",
  "TypeScript",
];
